# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np 

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
np.__version__

'2.1.3'

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
x = np.zeros((5,2))
x.size

10

#### 4. How to find the memory size of any array (★☆☆)

In [5]:
x.dtype

dtype('float64')

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its or

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
y = np.zeros((5,2))
y[0:,-1] = 1
y

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.]])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
vector = np.arange(1,11)
rev_vector = vector[::-1]
rev_vector

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
matrix = np.arange(9).reshape(3, 3)

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
arr = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(arr)
print(non_zero_indices[0])

[0 1 4]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
random_array = np.random.random((3, 3, 3))

print(random_array)

[[[0.34060731 0.72835777 0.12488881]
  [0.92929517 0.70107636 0.3573226 ]
  [0.55930317 0.49070884 0.80795891]]

 [[0.02985779 0.72055932 0.72228915]
  [0.36287204 0.48592823 0.027781  ]
  [0.08293684 0.25004318 0.67458615]]

 [[0.68061898 0.28248251 0.32449014]
  [0.87460502 0.42586239 0.61868109]
  [0.11015931 0.12669362 0.99604731]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:


random = np.random.random((10,10))
max = np.max(random)
min = np.min(random)
        
print(random,max,min)

[[4.63969233e-05 5.99119130e-01 8.21826720e-01 7.71270300e-01
  3.62277947e-01 3.70656562e-01 6.18924878e-01 8.02508714e-01
  1.45179436e-01 9.44797946e-01]
 [7.61742539e-01 4.04692139e-01 7.57383499e-01 8.06325445e-01
  4.70708216e-01 7.76521488e-02 8.86395712e-01 8.15672023e-01
  1.26722528e-02 1.69620616e-01]
 [9.96443408e-01 3.42841352e-01 7.98333119e-01 6.98365090e-01
  1.24994944e-01 2.01584584e-01 5.39938912e-01 4.56384544e-01
  6.49146958e-01 9.98204737e-01]
 [5.00023792e-02 1.84072530e-01 4.14927120e-01 6.13981655e-01
  6.22507881e-02 1.54980490e-01 5.71393057e-01 1.06514059e-01
  5.89401109e-01 2.48920286e-01]
 [3.94501431e-01 7.18160974e-01 6.96322682e-01 7.80644395e-01
  9.81776240e-01 3.47932177e-01 9.55959137e-01 2.54630366e-01
  4.82619854e-01 1.99965950e-01]
 [2.46067968e-01 2.49736157e-01 6.79565797e-01 7.50384798e-01
  8.23406205e-01 1.50111659e-01 6.31628369e-01 2.07869059e-01
  6.28135577e-01 4.10655661e-01]
 [3.47313649e-01 4.82826496e-01 4.00384848e-01 6.58597210e

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
random_vector = np.random.random(30)

mean_value = np.mean(random_vector)

print("Random Vector:\n", random_vector)
print("Mean Value:", mean_value)

Random Vector:
 [0.02768739 0.31501016 0.93639484 0.25178424 0.58926832 0.78505244
 0.74108917 0.40581468 0.22953536 0.20887717 0.97399463 0.48305638
 0.46619528 0.59614967 0.94002239 0.22720708 0.61507834 0.20608107
 0.59411165 0.04696313 0.0689414  0.82484892 0.51924467 0.85540975
 0.36130455 0.30472123 0.48374739 0.95220332 0.17534536 0.76691862]
Mean Value: 0.49840195378543917


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
rows, cols = 5, 5


array = np.zeros((rows, cols), dtype=int)


array[0, :] = 1         
array[-1, :] = 1       
array[:, 0] = 1         
array[:, -1] = 1        

print(array)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
rows, cols = 5, 5


array = np.ones((rows, cols), dtype=int)


array[0, :] = 0         
array[-1, :] = 0      
array[:, 0] = 0        
array[:, -1] = 0        

print(array)

[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [18]:
False

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [19]:
matrix = np.zeros((5, 5))


for i in range(1, 5):
    matrix[i, i-1] = i

print(matrix)


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [20]:
checkerboard = np.indices((8, 8)).sum(axis=0) % 2

print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [21]:
checkerboard_2x2 = np.array([[0, 1], [1, 0]])


checkerboard_8x8 = np.tile(checkerboard_2x2, (4, 4))

print(checkerboard_8x8)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [22]:
array = np.random.random((5*5))
array

array([0.10645087, 0.19445374, 0.66126634, 0.3285309 , 0.56805553,
       0.66965425, 0.59062073, 0.03628358, 0.01071886, 0.15901929,
       0.14050853, 0.24655898, 0.49593379, 0.89472137, 0.04979094,
       0.41307283, 0.52053883, 0.60648166, 0.74568305, 0.33809324,
       0.5165446 , 0.76492545, 0.88665148, 0.55614124, 0.41436553])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [23]:
rgba_dtype = np.dtype([('r', np.uint8), ('g', np.uint8), ('b', np.uint8), ('a', np.uint8)])


colors = np.array([(255, 0, 0, 255), (0, 255, 0, 255), (0, 0, 255, 255)], dtype=rgba_dtype)

print(colors)

[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [24]:
import numpy as np


A = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9], 
              [10, 11, 12], 
              [13, 14, 15]])

B = np.array([[1, 2], 
              [3, 4], 
              [5, 6]])


C = np.dot(A, B) 

print(C)


[[ 22  28]
 [ 49  64]
 [ 76 100]
 [103 136]
 [130 172]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [25]:
import numpy as np


arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])


arr[(arr >= 3) & (arr <= 8)] = -arr[(arr >= 3) & (arr <= 8)]

print(arr)


[ 1  2 -3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [26]:
9


9

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [27]:
Z = np.array([1, 2, 3])

try:
    print("Z**Z:", Z**Z)  
except Exception as e:
    print("Z**Z: Error -", e)

try:
    print("2 << Z >> 2:", 2 << Z >> 2) 
except Exception as e:
    print("2 << Z >> 2: Error -", e)

try:
    print("Z <- Z:", Z <- Z) 
except Exception as e:
    print("Z <- Z: Error -", e)

try:
    print("1j*Z:", 1j * Z) 
except Exception as e:
    print("1j*Z: Error -", e)

try:
    print("Z/1/1:", Z / 1 / 1)  
except Exception as e:
    print("Z/1/1: Error -", e)

try:
    print("Z<Z>Z:", Z < Z > Z) 
except Exception as e:
    print("Z<Z>Z: Error -", e)

Z**Z: [ 1  4 27]
2 << Z >> 2: [1 2 4]
Z <- Z: [False False False]
1j*Z: [0.+1.j 0.+2.j 0.+3.j]
Z/1/1: [1. 2. 3.]
Z<Z>Z: Error - The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [28]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\User\AppData\Local\Temp\ipykernel_9840\548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
C:\Users\User\AppData\Local\Temp\ipykernel_9840\548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
C:\Users\User\AppData\Local\Temp\ipykernel_9840\548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [29]:
arr = np.array([-1.5, -2.3, 0, 1.2, 2.7])

# Round away from zero
rounded = np.where(arr > 0, np.ceil(arr), np.floor(arr))

print("Original array:", arr)
print("Rounded away from zero:", rounded)

Original array: [-1.5 -2.3  0.   1.2  2.7]
Rounded away from zero: [-2. -3.  0.  2.  3.]


#### 30. How to find common values between two arrays? (★☆☆)

In [30]:
Z1 = np.random.randint(0,100,10)
Z2 = np.random.randint(0,100,10)
print(np.intersect1d(Z1,Z2))

[53 73]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [31]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\User\AppData\Local\Temp\ipykernel_9840\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [32]:


from datetime import datetime, timedelta

# Get today's date
today = datetime.today().date()

# Calculate yesterday and tomorrow
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2024-11-15
Today: 2024-11-16
Tomorrow: 2024-11-17


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [33]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [34]:
A = np.array([2.0, 4.0])
B = np.array([1.0, 3.0])

A *= -0.5
A += B
A *= A - B

print(A)

[-0. -2.]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
arr = np.random.rand(5) * 100

int_part1 = arr.astype(int)
int_part2 = np.floor(arr).astype(int)
int_part3 = np.trunc(arr).astype(int)
int_part4 = np.array(arr, dtype=int)

print(int_part1, int_part2, int_part3, int_part4)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [35]:
matrix = np.tile(np.arange(5), (5, 1))
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [36]:
gen = (i for i in range(10))
arr = np.fromiter(gen, dtype=int, count=10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [37]:
vector = np.linspace(0, 1, 12)[1:-1]
print(vector)


[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
vector = np.random.rand(10)
vector.sort()
print(vector)

[0.01373606 0.14110146 0.49015774 0.52647486 0.66121256 0.67437988
 0.70607326 0.75606194 0.81029372 0.8839721 ]


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [39]:

A = np.random.randint(0, 10, size=5)
B = np.random.randint(0, 10, size=5)

if np.array_equal(A, B):
    print("Arrays A and B are equal.")
else:
    print("Arrays A and B are not equal.")

Arrays A and B are not equal.


#### 43. Make an array immutable (read-only) (★★☆)

In [40]:

A = np.random.randint(0, 10, size=5)
A.flags.writeable = False

try:
    A[0] = 5
except ValueError as e:
    print("Error:", e)

Error: assignment destination is read-only


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [41]:
A = np.random.rand(10, 2)

x = A[:, 0]
y = A[:, 1]

r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)

polar_coordinates = np.column_stack((r, theta))

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [43]:

A = np.random.rand(10)

A[A.argmax()] = 0
A

array([0.08406204, 0.38734764, 0.8439459 , 0.62021472, 0.79687007,
       0.74086838, 0.0515886 , 0.        , 0.57534995, 0.02144384])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [45]:
x = np.linspace(0, 1, 10)
y = np.linspace(0, 1, 10)

x_grid, y_grid = np.meshgrid(x, y)

coordinates = np.zeros(x_grid.size, dtype=[('x', float), ('y', float)])
coordinates['x'] = x_grid.flatten()
coordinates['y'] = y_grid.flatten()
coordinates

array([(0.        , 0.        ), (0.11111111, 0.        ),
       (0.22222222, 0.        ), (0.33333333, 0.        ),
       (0.44444444, 0.        ), (0.55555556, 0.        ),
       (0.66666667, 0.        ), (0.77777778, 0.        ),
       (0.88888889, 0.        ), (1.        , 0.        ),
       (0.        , 0.11111111), (0.11111111, 0.11111111),
       (0.22222222, 0.11111111), (0.33333333, 0.11111111),
       (0.44444444, 0.11111111), (0.55555556, 0.11111111),
       (0.66666667, 0.11111111), (0.77777778, 0.11111111),
       (0.88888889, 0.11111111), (1.        , 0.11111111),
       (0.        , 0.22222222), (0.11111111, 0.22222222),
       (0.22222222, 0.22222222), (0.33333333, 0.22222222),
       (0.44444444, 0.22222222), (0.55555556, 0.22222222),
       (0.66666667, 0.22222222), (0.77777778, 0.22222222),
       (0.88888889, 0.22222222), (1.        , 0.22222222),
       (0.        , 0.33333333), (0.11111111, 0.33333333),
       (0.22222222, 0.33333333), (0.33333333, 0.33333333

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [46]:
scalar_types = [np.int8, np.int16, np.int32, np.int64, np.uint8, np.uint16, np.uint32, np.uint64,
                np.float16, np.float32, np.float64, np.complex64, np.complex128]

for dtype in scalar_types:
    if np.issubdtype(dtype, np.integer):
        print(f"{dtype}: Min = {np.iinfo(dtype).min}, Max = {np.iinfo(dtype).max}")
    else:
        print(f"{dtype}: Min = {np.finfo(dtype).min}, Max = {np.finfo(dtype).max}")

<class 'numpy.int8'>: Min = -128, Max = 127
<class 'numpy.int16'>: Min = -32768, Max = 32767
<class 'numpy.int32'>: Min = -2147483648, Max = 2147483647
<class 'numpy.int64'>: Min = -9223372036854775808, Max = 9223372036854775807
<class 'numpy.uint8'>: Min = 0, Max = 255
<class 'numpy.uint16'>: Min = 0, Max = 65535
<class 'numpy.uint32'>: Min = 0, Max = 4294967295
<class 'numpy.uint64'>: Min = 0, Max = 18446744073709551615
<class 'numpy.float16'>: Min = -65504.0, Max = 65504.0
<class 'numpy.float32'>: Min = -3.4028234663852886e+38, Max = 3.4028234663852886e+38
<class 'numpy.float64'>: Min = -1.7976931348623157e+308, Max = 1.7976931348623157e+308
<class 'numpy.complex64'>: Min = -3.4028234663852886e+38, Max = 3.4028234663852886e+38
<class 'numpy.complex128'>: Min = -1.7976931348623157e+308, Max = 1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [47]:
arr = np.random.rand(100)  

np.set_printoptions(threshold=np.inf) 
print(arr)

[0.57352902 0.2435075  0.51515567 0.00970805 0.81826799 0.35298743
 0.1941184  0.02359711 0.48835919 0.15187076 0.64214816 0.71918341
 0.42337456 0.54598447 0.55798551 0.70099354 0.12191196 0.5488271
 0.9596285  0.12678841 0.71579188 0.35715439 0.96385491 0.22770815
 0.90587657 0.36803277 0.40952331 0.39953726 0.070554   0.30162071
 0.51425765 0.73533727 0.45687898 0.38397437 0.06339234 0.90986132
 0.03046059 0.75377363 0.80410229 0.52065703 0.20628275 0.85665948
 0.73941082 0.96961225 0.14163263 0.39724622 0.37674414 0.114964
 0.17973433 0.27897177 0.99995899 0.40044722 0.41793162 0.82659621
 0.40146263 0.89123601 0.30168629 0.34130709 0.83697499 0.98415479
 0.36720777 0.44317882 0.7902403  0.12427434 0.3477362  0.80131671
 0.85743277 0.01117614 0.17531497 0.17412928 0.06130794 0.79995734
 0.23307932 0.5444551  0.07418481 0.33998074 0.92337722 0.71344729
 0.93740949 0.36517824 0.60027143 0.56934697 0.37496455 0.16709757
 0.46022798 0.32001683 0.06616148 0.99580235 0.96070443 0.3254077

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [48]:
arr = np.array([1, 3, 7, 9, 12])
scalar = 8


closest_value = arr[np.abs(arr - scalar).argmin()]

print(f"The closest value to {scalar} is {closest_value}")

The closest value to 8 is 7


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [49]:
arr = np.array([1, 3, 7, 15, 255])


binary_matrix = np.vectorize(lambda x: format(x, '08b'))(arr)

print(binary_matrix)

['00000001' '00000011' '00000111' '00001111' '11111111']


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [50]:
arr = np.array([[1, 2], [3, 4], [1, 2], [5, 6]])

unique_rows = np.unique(arr, axis=0)

print(unique_rows)

[[1 2]
 [3 4]
 [5 6]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [51]:
X = np.array([0, 1, 2, 3, 4])
Y = np.array([0, 1, 4, 9, 16])


distances = np.sqrt(np.diff(X)**2 + np.diff(Y)**2)


cumulative_distance = np.concatenate(([0], np.cumsum(distances)))

total_length = cumulative_distance[-1]

num_samples = 10


sample_distances = np.linspace(0, total_length, num_samples)


sample_X = np.interp(sample_distances, cumulative_distance, X)
sample_Y = np.interp(sample_distances, cumulative_distance, Y)


sampled_points = np.column_stack((sample_X, sample_Y))
print(sampled_points)

[[ 0.          0.        ]
 [ 1.1412012   1.42360359]
 [ 1.72961599  3.18884796]
 [ 2.19723432  4.98617158]
 [ 2.56215368  6.81076839]
 [ 2.92707304  8.6353652 ]
 [ 3.21055872 10.47391102]
 [ 3.47370581 12.31594068]
 [ 3.73685291 14.15797034]
 [ 4.         16.        ]]


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)